server:
  port: 80
zuul:
  routes:
    posts:
      path: /posts-management/**
      serviceId: posts
    users:
      path: /users-management/**
      serviceId: users

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
